services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  kafbat-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    depends_on:
      - kafka
      - connect
    ports:
      - "9091:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  # -------- Postgres --------
  post_db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: post_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    volumes:
      - post_db_data:/var/lib/postgresql/data
    command: >
      postgres -c wal_level=logical -c max_wal_senders=10 -c max_replication_slots=10

  user_db:
    image: postgres:16
    ports:
        - "5434:5432"
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    volumes:
      - user_db_data:/var/lib/postgresql/data

  notification_db:
    image: postgres:16
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    volumes:
      - notification_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    platform: linux/amd64
    depends_on:
      - post_db
      - user_db
      - notification_db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: changeme
    # volumes:
    #   - pgadmin_data:/var/lib/pgadmin

  # -------- Neo4j --------
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/changeme
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  # -------- Kafka Connect with Debezium --------
  connect:
    image: quay.io/debezium/connect:3.1
    depends_on: [kafka, post_db]
    ports:
      - "9090:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=connect-cluster
      - CONFIG_STORAGE_TOPIC=connect-configs
      - OFFSET_STORAGE_TOPIC=connect-offsets
      - STATUS_STORAGE_TOPIC=connect-status
      - CONNECT_REST_ADVERTISED_HOST_NAME=connect

      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false

  # -------- Zipkin --------
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"

volumes:
  post_db_data:
  user_db_data:
  notification_db_data:
  neo4j_data:
  neo4j_logs: